# Generated by Django 5.1.3 on 2024-11-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_location_address_1_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(max_length=8),
        ),
    ]
