# Generated by Django 5.1.3 on 2024-11-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_likedlisting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedListing',
        ),
    ]
